import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { bebas_neue, poppins } from "./fonts";

const pduRegular = localFont({
  src: "./fonts/pdu-regular.ttf",
  variable: "--font-pdu-regular",
});

export const metadata: Metadata = {
  title: "Burgers With Benefits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${bebas_neue.variable} ${pduRegular.variable} ${poppins.variable}`}
    >
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
